using System.Collections.Frozen;

namespace GuluPet.Runtime;

public static class RuntimeClipInventory
{
    public static FrozenSet<string> ClipIds { get; } = new[]
    {
        "idle_breathe", "idle_forepaw_reset", "idle_tail_rewrap",
        "idle_ear_scratch_reset", "idle_floor_scent_check",
        "blink_slow", "stretch_forward", "groom_chest",
        "sleep_enter", "sleep_loop", "sleep_exit",
        "sleep_enter_b", "sleep_loop_b", "sleep_exit_b",
        "sleep_enter_c", "sleep_loop_c", "sleep_exit_c",
        "head_raise", "head_tilt", "ear_perk", "ear_orient_right",
        "ear_orient_both", "tail_tip_sway", "vocalize_short", "paw_reach",
        "drag_hold_relaxed", "drag_hold_tense", "drag_hold_stretched",
        "shake_body", "wake_startle",
        "loaf_enter", "loaf_loop", "loaf_exit", "watch_enter", "watch_loop",
        "watch_exit", "body_relax", "relaxed_breathe", "body_unrelax",
        "crouch_enter", "crouch_watch", "crouch_exit", "sprawl_enter",
        "sprawl_loop", "sprawl_exit", "curl_tight_enter", "curl_tight_loop",
        "curl_tight_exit", "doze_enter", "doze_loop", "wake_slow",
        "groom_paw", "groom_face", "groom_side", "yawn_full", "lick_nose",
        "paw_knead", "roll_side_and_back", "nose_tuck", "slow_side_shift",
        "stretch_forelegs", "drowsy_nod", "sniff_air", "head_scan",
        "look_side_fast", "look_side_slow", "ear_orient_left_right",
        "ears_flat_enter",
        "ears_flat_loop", "ears_relax", "tail_focus_irregular", "sniff_left",
        "head_turn_right",
        "chin_rest_enter", "chin_rest_loop", "chin_rest_exit",
        "sit_tall_enter", "sit_tall_watch", "sit_tall_exit", "wait_sit_enter",
        "wait_sit", "wait_sit_exit", "compact_rest_enter",
        "compact_rest_loop", "compact_rest_exit", "tight_loaf_enter",
        "tight_loaf_loop", "tight_loaf_exit",
        "jump_high_land", "rear_up_boxing", "side_hop_startle",
        "pounce_forward_recover", "tail_chase_spin",
        "click_pop_up_greet", "click_paw_highfive", "click_happy_hop",
        "click_side_flop", "click_tail_up_half_turn",
        "repeat_double_paw_catch", "repeat_bunny_kick_roll",
        "repeat_backhop_return", "repeat_full_turn_protest",
        "longpress_full_cheek_rub", "longpress_side_roll_offer",
        "longpress_forepaw_hug", "longpress_elevator_butt",
        "longpress_arch_push", "pet_headbutt_step_through",
        "pet_side_to_side_roll", "pet_knead_bounce",
        "pet_tail_quiver_tread", "pet_crescent_stretch",
        "pet_end_follow_nuzzle", "pet_end_paw_hook",
        "pet_end_long_sploot", "pet_end_roll_request",
        "pet_end_tail_hook_turn", "hover_rear_up_inspect",
        "hover_paw_tap_recoil", "hover_side_scoot_peek",
        "hover_belly_crawl_probe", "hover_jump_sniff",
        "approach_alert_crouch", "approach_welcome_hop",
        "approach_roll_intercept", "approach_under_hand_arch",
        "rapid_leap_turn", "rapid_low_slide_swat", "rapid_duck_pop",
        "rapid_two_bound_chase", "circle_walk_orbit",
        "circle_rear_trace", "circle_low_orbit_swat",
        "circle_roll_follow", "circle_continuous_walk_loop",
        "drag_release_spring_land",
        "drag_release_pivot_recover", "drag_release_stretch_reset",
        "drag_release_roll_reset",
        "eat_cat_treat", "drink_water",
    }.ToFrozenSet(StringComparer.Ordinal);

    public static FrozenSet<string> LoopClipIds { get; } = new[]
    {
        "idle_breathe",
        "sleep_loop",
        "sleep_loop_b",
        "sleep_loop_c",
        "tail_tip_sway",
        "drag_hold_relaxed",
        "drag_hold_tense",
        "drag_hold_stretched",
        "loaf_loop",
        "watch_loop",
        "relaxed_breathe",
        "crouch_watch",
        "sprawl_loop",
        "curl_tight_loop",
        "doze_loop",
        "paw_knead",
        "ears_flat_loop",
        "tail_focus_irregular",
        "chin_rest_loop",
        "sit_tall_watch",
        "wait_sit",
        "compact_rest_loop",
        "tight_loaf_loop",
        "circle_continuous_walk_loop",
    }.ToFrozenSet(StringComparer.Ordinal);
}
